"""knowledge graph: topics, clusters, edges, embeddings

Revision ID: 1939bd7fcc3b
Revises: 02944ffb40a4
Create Date: 2026-06-01 17:21:47.959258
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "1939bd7fcc3b"
down_revision: Union[str, None] = "02944ffb40a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector extension must exist before the embedding column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "graph_edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("relation", sa.String(length=40), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_graph_edges_project_id"), "graph_edges", ["project_id"], unique=False
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topics_project_id"), "topics", ["project_id"], unique=False
    )
    op.add_column("clusters", sa.Column("topic_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_clusters_topic_id"), "clusters", ["topic_id"], unique=False
    )
    op.create_foreign_key(
        None, "clusters", "topics", ["topic_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("keywords", sa.Column("cluster_id", sa.Uuid(), nullable=True))
    op.add_column(
        "keywords",
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=768).with_variant(
                sa.JSON(), "sqlite"
            ),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_keywords_cluster_id"), "keywords", ["cluster_id"], unique=False
    )
    op.create_unique_constraint(None, "keywords", ["project_id", "keyword"])
    op.create_foreign_key(
        None, "keywords", "clusters", ["cluster_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "keywords", type_="foreignkey")
    op.drop_constraint(None, "keywords", type_="unique")
    op.drop_index(op.f("ix_keywords_cluster_id"), table_name="keywords")
    op.drop_column("keywords", "embedding")
    op.drop_column("keywords", "cluster_id")
    op.drop_constraint(None, "clusters", type_="foreignkey")
    op.drop_index(op.f("ix_clusters_topic_id"), table_name="clusters")
    op.drop_column("clusters", "topic_id")
    op.drop_index(op.f("ix_topics_project_id"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_graph_edges_project_id"), table_name="graph_edges")
    op.drop_table("graph_edges")
    # ### end Alembic commands ###
