"""org clerk + stripe ids

Revision ID: fba55a66554c
Revises: 1939bd7fcc3b
Create Date: 2026-06-01 19:46:53.216293
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fba55a66554c"
down_revision: Union[str, None] = "1939bd7fcc3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("clerk_org_id", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "organizations",
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
    )
    op.create_unique_constraint(None, "organizations", ["clerk_org_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organizations", type_="unique")
    op.drop_column("organizations", "stripe_customer_id")
    op.drop_column("organizations", "clerk_org_id")
    # ### end Alembic commands ###
